(* let spec_path = "/home/bordo/Git/ortac/plugins/qcheck-pbt/test/specs/spec.mli" *)

let%expect_test "list rev spec generates" =
  let spec = 
    {|val list_rev : int list -> int list
    (*@ revved = list_rev l
        ensures l = List.rev revved
        pure
    *)|} in

  let spec_dir = Filename.temp_dir "temp" "spec" in
  let spec_file = spec_dir ^ "/" ^ "spec.mli" in
  let oc = open_out spec_file in

  Out_channel.output_string oc spec;
  Out_channel.flush_all ();

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let list_rev_property l =
      let revved = list_rev l in l = (Ortac_runtime.Gospelstdlib.List.rev revved)
    |}]



(* let%expect_test "addition" = *)
  (* Printf.printf "%d" (1 + 2); *)
  (* [%expect {| 3 |}] *)
(* ;; *)
