(* let spec_path = "/home/bordo/Git/ortac/plugins/qcheck-pbt/test/specs/spec.mli" *)

let _ = List.map

let write_spec_to_temp spec = 
  let spec_dir = Filename.temp_dir "temp" "spec" in
  let spec_file = spec_dir ^ "/" ^ "spec.mli" in

  Out_channel.with_open_text spec_file (fun oc -> 
    Out_channel.output_string oc spec;
    Out_channel.flush_all ());
  spec_file

let%expect_test "list rev spec generates" =
  let spec = 
    {|val list_rev : int list -> int list
    (*@ revved = list_rev l
        ensures l = List.rev revved
        pure
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    Warning: Instantiating polymorphic type 'list' with 'int'
    Warning: Instantiating polymorphic type 'list' with 'int'
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let list_rev_property l =
      let revved = list_rev l in l = (Ortac_runtime.Gospelstdlib.List.rev revved)
    let list_rev_test =
      QCheck.Test.make ~count:100 ~name:"list_rev"
        (QCheck.Gen.list QCheck.Gen.int) list_rev_property
    let () = QCheck_base_runner.run_tests_main [list_rev_test]
    |}]



(* let%expect_test "addition" = *)
  (* Printf.printf "%d" (1 + 2); *)
  (* [%expect {| 3 |}] *)
(* ;; *)
