(* let spec_path = "/home/bordo/Git/ortac/plugins/qcheck-pbt/test/specs/spec.mli" *)

let _ = List.map

let write_spec_to_temp spec = 
  let spec_dir = Filename.temp_dir "temp" "spec" in
  let spec_file = spec_dir ^ "/" ^ "spec.mli" in

  Out_channel.with_open_text spec_file (fun oc -> 
    Out_channel.output_string oc spec;
    Out_channel.flush_all ());
  spec_file

let%expect_test "list rev spec generates" =
  let spec = 
    {|val list_rev : int list -> int list
    (*@ revved = list_rev l
        ensures l = List.rev revved
        pure
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    Warning: Instantiating polymorphic type 'list' with 'int'
    Warning: Instantiating polymorphic type 'list' with 'int'
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let list_rev_property l =
      let revved = list_rev l in l = (Ortac_runtime.Gospelstdlib.List.rev revved)
    let list_rev_test =
      QCheck.Test.make ~count:100 ~name:"list_rev" (QCheck.list QCheck.int)
        list_rev_property
    let () = QCheck_base_runner.run_tests_main [list_rev_test]
    |}]



(* Test basic type generators *)

let%expect_test "int type generates QCheck.Gen.int" =
  let spec =
    {|val abs : int -> int
    (*@ result = abs x
        ensures result >= 0
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let abs_property x =
      let result = abs x in
      Ortac_runtime.Gospelstdlib.(>=)
        (Ortac_runtime.Gospelstdlib.integer_of_int result)
        (Ortac_runtime.Gospelstdlib.integer_of_int 0)
    let abs_test =
      QCheck.Test.make ~count:100 ~name:"abs" QCheck.int abs_property
    let () = QCheck_base_runner.run_tests_main [abs_test]
    |}]

let%expect_test "string type generates QCheck.Gen.string" =
  let spec =
    {|val string_length : string -> int
    (*@ len = string_length s
        ensures len >= 0
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let string_length_property s =
      let len = string_length s in
      Ortac_runtime.Gospelstdlib.(>=)
        (Ortac_runtime.Gospelstdlib.integer_of_int len)
        (Ortac_runtime.Gospelstdlib.integer_of_int 0)
    let string_length_test =
      QCheck.Test.make ~count:100 ~name:"string_length" QCheck.string
        string_length_property
    let () = QCheck_base_runner.run_tests_main [string_length_test]
    |}]

let%expect_test "bool type generates QCheck.Gen.bool" =
  let spec =
    {|val bool_not : bool -> bool
    (*@ result = bool_not b
        ensures result = not b
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let bool_not_property b =
      let result_1 = bool_not b in
      result_1 = (if not (b = true) then true else false)
    let bool_not_test =
      QCheck.Test.make ~count:100 ~name:"bool_not" QCheck.bool bool_not_property
    let () = QCheck_base_runner.run_tests_main [bool_not_test]
    |}]

(* Test preconditions *)

let%expect_test "function with precondition generates QCheck.assume" =
  let spec =
    {|val divide : int -> int -> int
    (*@ result = divide x y
        requires y <> 0
        ensures result * y = x
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let divide_property x_1 y =
      QCheck.assume
        (not
           ((Ortac_runtime.Gospelstdlib.integer_of_int y) =
              (Ortac_runtime.Gospelstdlib.integer_of_int 0)));
      (let result_2 = divide x_1 y in
       (Ortac_runtime.Gospelstdlib.( * )
          (Ortac_runtime.Gospelstdlib.integer_of_int result_2)
          (Ortac_runtime.Gospelstdlib.integer_of_int y))
         = (Ortac_runtime.Gospelstdlib.integer_of_int x_1))
    let divide_test =
      QCheck.Test.make ~count:100 ~name:"divide"
        (QCheck.pair QCheck.int QCheck.int) divide_property
    let () = QCheck_base_runner.run_tests_main [divide_test]
    |}]

let%expect_test "function with multiple preconditions" =
  let spec =
    {|val safe_divide : int -> int -> int
    (*@ result = safe_divide x y
        requires y <> 0
        requires x >= 0
        ensures result >= 0
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let safe_divide_property x_2 y_1 =
      QCheck.assume
        (not
           ((Ortac_runtime.Gospelstdlib.integer_of_int y_1) =
              (Ortac_runtime.Gospelstdlib.integer_of_int 0)));
      QCheck.assume
        (Ortac_runtime.Gospelstdlib.(>=)
           (Ortac_runtime.Gospelstdlib.integer_of_int x_2)
           (Ortac_runtime.Gospelstdlib.integer_of_int 0));
      (let result_3 = safe_divide x_2 y_1 in
       Ortac_runtime.Gospelstdlib.(>=)
         (Ortac_runtime.Gospelstdlib.integer_of_int result_3)
         (Ortac_runtime.Gospelstdlib.integer_of_int 0))
    let safe_divide_test =
      QCheck.Test.make ~count:100 ~name:"safe_divide"
        (QCheck.pair QCheck.int QCheck.int) safe_divide_property
    let () = QCheck_base_runner.run_tests_main [safe_divide_test]
    |}]

(* Test multi-argument functions *)

let%expect_test "two argument function uses QCheck.pair" =
  let spec =
    {|val add : int -> int -> int
    (*@ result = add x y
        ensures result = x + y
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let add_property x_3 y_2 =
      let result_4 = add x_3 y_2 in
      (Ortac_runtime.Gospelstdlib.integer_of_int result_4) =
        (Ortac_runtime.Gospelstdlib.(+)
           (Ortac_runtime.Gospelstdlib.integer_of_int x_3)
           (Ortac_runtime.Gospelstdlib.integer_of_int y_2))
    let add_test =
      QCheck.Test.make ~count:100 ~name:"add" (QCheck.pair QCheck.int QCheck.int)
        add_property
    let () = QCheck_base_runner.run_tests_main [add_test]
    |}]

let%expect_test "three argument function uses QCheck.triple" =
  let spec =
    {|val add3 : int -> int -> int -> int
    (*@ result = add3 x y z
        ensures result = x + y + z
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let add3_property x_4 y_3 z =
      let result_5 = add3 x_4 y_3 z in
      (Ortac_runtime.Gospelstdlib.integer_of_int result_5) =
        (Ortac_runtime.Gospelstdlib.(+)
           (Ortac_runtime.Gospelstdlib.(+)
              (Ortac_runtime.Gospelstdlib.integer_of_int x_4)
              (Ortac_runtime.Gospelstdlib.integer_of_int y_3))
           (Ortac_runtime.Gospelstdlib.integer_of_int z))
    let add3_test =
      QCheck.Test.make ~count:100 ~name:"add3"
        (QCheck.triple QCheck.int QCheck.int QCheck.int) add3_property
    let () = QCheck_base_runner.run_tests_main [add3_test]
    |}]

let%expect_test "four argument function uses QCheck.quad" =
  let spec =
    {|val add4 : int -> int -> int -> int -> int
    (*@ result = add4 w x y z
        ensures result = w + x + y + z
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let add4_property w x_5 y_4 z_1 =
      let result_6 = add4 w x_5 y_4 z_1 in
      (Ortac_runtime.Gospelstdlib.integer_of_int result_6) =
        (Ortac_runtime.Gospelstdlib.(+)
           (Ortac_runtime.Gospelstdlib.(+)
              (Ortac_runtime.Gospelstdlib.(+)
                 (Ortac_runtime.Gospelstdlib.integer_of_int w)
                 (Ortac_runtime.Gospelstdlib.integer_of_int x_5))
              (Ortac_runtime.Gospelstdlib.integer_of_int y_4))
           (Ortac_runtime.Gospelstdlib.integer_of_int z_1))
    let add4_test =
      QCheck.Test.make ~count:100 ~name:"add4"
        (QCheck.quad QCheck.int QCheck.int QCheck.int QCheck.int) add4_property
    let () = QCheck_base_runner.run_tests_main [add4_test]
    |}]

(* Test multi-return functions *)

let%expect_test "function returning tuple" =
  let spec =
    {|val div_mod : int -> int -> int * int
    (*@ (q, r) = div_mod x y
        requires y > 0
        ensures x = (q * y) + r
        ensures r >= 0
        ensures r < y
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let div_mod_property x_6 y_5 =
      QCheck.assume
        (Ortac_runtime.Gospelstdlib.(>)
           (Ortac_runtime.Gospelstdlib.integer_of_int y_5)
           (Ortac_runtime.Gospelstdlib.integer_of_int 0));
      (let (q, r) = div_mod x_6 y_5 in
       (((Ortac_runtime.Gospelstdlib.integer_of_int x_6) =
           (Ortac_runtime.Gospelstdlib.(+)
              (Ortac_runtime.Gospelstdlib.( * )
                 (Ortac_runtime.Gospelstdlib.integer_of_int q)
                 (Ortac_runtime.Gospelstdlib.integer_of_int y_5))
              (Ortac_runtime.Gospelstdlib.integer_of_int r)))
          &&
          (Ortac_runtime.Gospelstdlib.(>=)
             (Ortac_runtime.Gospelstdlib.integer_of_int r)
             (Ortac_runtime.Gospelstdlib.integer_of_int 0)))
         &&
         (Ortac_runtime.Gospelstdlib.(<)
            (Ortac_runtime.Gospelstdlib.integer_of_int r)
            (Ortac_runtime.Gospelstdlib.integer_of_int y_5)))
    let div_mod_test =
      QCheck.Test.make ~count:100 ~name:"div_mod"
        (QCheck.pair QCheck.int QCheck.int) div_mod_property
    let () = QCheck_base_runner.run_tests_main [div_mod_test]
    |}]

(* Test unit return *)

let%expect_test "function returning unit" =
  let spec =
    {|val print_int : int -> unit
    (*@ print_int x
        ensures true
    *)|} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect.unreachable]
[@@expect.uncaught_exn {|
  (* CR expect_test_collector: This test expectation appears to contain a backtrace.
     This is strongly discouraged as backtraces are fragile.
     Please change this test to not include a backtrace. *)
  ("Gospel.Warnings.Error(_)")
  Raised at Gospel__Warnings.error in file "src/warnings.ml", line 51, characters 19-41
  Called from Gospel__Typing.process_val in file "src/typing.ml", line 1016, characters 12-67
  Called from Gospel__Typing.process_sig_item.process_sig_item in file "src/typing.ml", line 1344, characters 31-67
  Called from Gospel__Typing.process_sig_item.process_and_import in file "src/typing.ml", line 1367, characters 8-31
  Called from Gospel__Typing.process_sig_item in file "src/typing.ml", line 1376, characters 23-51
  Called from Gospel__Typing.type_sig_item in file "src/typing.ml" (inlined), line 1381, characters 15-49
  Called from Ortac_core__Utils.type_check in file "src/core/utils.ml", line 20, characters 29-56
  Called from Stdlib__List.fold_left in file "list.ml", line 123, characters 24-34
  Called from Ortac_core__Utils.type_check in file "src/core/utils.ml", line 20, characters 14-64
  Called from Ortac_qcheck_pbt__Generate.generate in file "plugins/qcheck-pbt/src/generate.ml", lines 302-303, characters 2-40
  Called from Ortac_qcheck_pbt_test__Test.(fun) in file "plugins/qcheck-pbt/test/test.ml", line 323, characters 2-67
  Called from Ppx_expect_runtime__Test_block.Configured.dump_backtrace in file "runtime/test_block.ml", line 142, characters 10-28
  |}]

(* Test multiple functions in one module *)

let%expect_test "multiple functions generate multiple tests" =
  let spec =
    {|val abs : int -> int
    (*@ result = abs x
        ensures result >= 0
    *)

    val square : int -> int
    (*@ result = square x
        ensures result = x * x
    *)
    |} in
  let spec_file = write_spec_to_temp spec in

  Ortac_qcheck_pbt.Generate.generate spec_file Format.std_formatter;

  [%expect {|
    (* This file is generated by ortac quickcheck,
       edit the original interface file instead *)
    include Spec
    let abs_property x_7 =
      let result_7 = abs x_7 in
      Ortac_runtime.Gospelstdlib.(>=)
        (Ortac_runtime.Gospelstdlib.integer_of_int result_7)
        (Ortac_runtime.Gospelstdlib.integer_of_int 0)
    let abs_test =
      QCheck.Test.make ~count:100 ~name:"abs" QCheck.int abs_property
    let square_property x_8 =
      let result_8 = square x_8 in
      (Ortac_runtime.Gospelstdlib.integer_of_int result_8) =
        (Ortac_runtime.Gospelstdlib.( * )
           (Ortac_runtime.Gospelstdlib.integer_of_int x_8)
           (Ortac_runtime.Gospelstdlib.integer_of_int x_8))
    let square_test =
      QCheck.Test.make ~count:100 ~name:"square" QCheck.int square_property
    let () = QCheck_base_runner.run_tests_main [abs_test; square_test]
    |}]
