module W = Ortac_core.Warnings
open Ppxlib
open Ortac_core.Builder
open Ir
module Context = Ortac_core.Context

let header =
  "(* This file is generated by ortac quickcheck,\n\
  \   edit the original interface file instead *)"

(* Extract just the translated expression from a term *)
let term_to_expr (t : Ir.term) : expression option =
  match t.translation with 
  | Error _ -> None 
  | Ok e -> Some e

(* Generate the property function for a value *)
let value_to_property (v : Ir.value) : expression option =
  (* Build the function arguments *)
  let pargs = List.map (fun a -> (a.label, pvar a.name)) v.arguments in
  
  (* Get the return pattern and variable *)
  let ret_var = match v.returns with
    | [] -> None
    | [ x ] -> Some x.name
    | _ -> None (* For now, skip multi-return *)
  in
  
  match ret_var with
  | None -> None
  | Some ret_name ->
      (* Build the function call *)
      let call_args = List.map (fun a -> (a.label, evar a.name)) v.arguments in
      let call = pexp_apply (evar v.name) call_args in
      
      (* Combine all postconditions into a single boolean expression *)
      let postcond_exprs = 
        List.filter_map term_to_expr v.postconditions 
      in
      
      let combined_postcond = match postcond_exprs with
        | [] -> ebool true
        | [ e ] -> e
        | exprs -> 
            List.fold_left 
              (fun acc e -> eapply (evar "(&&)") [ acc; e ]) 
              (List.hd exprs) 
              (List.tl exprs)
      in
      
      (* Build: fun args -> let ret = call args in postconditions *)
      let body = 
        pexp_let Nonrecursive 
          [ value_binding ~pat:(pvar ret_name) ~expr:call ]
          combined_postcond
      in
      
      Some (efun pargs body)

(* Convert a value specification to a Ppxlib structure item *)
let value (v : Ir.value) : Ppxlib.structure_item list =
  match value_to_property v with
  | None -> []
  | Some prop_expr ->
      let prop_name = v.name ^ "_property" in
      let vb = value_binding ~pat:(pvar prop_name) ~expr:prop_expr in
      [ pstr_value Nonrecursive [ vb ] ]

(* Main structure generation *)
let structure _runtime module_name ir : Ppxlib.structure =
  (pmod_ident (lident module_name) |> include_infos |> pstr_include)
  :: (Ir.map_translation ir ~f:(function
        | Ir.Value v -> value v
        | _ -> [] (* Skip other items for now *)
     )
     |> List.flatten)

let signature ~runtime ~module_name namespace s =
  let open Ortac_core in
  let context = Context.init module_name namespace in
  let ir = Ir_of_gospel.signature ~context s in
  Report.emit_warnings Fmt.stderr ir;
  structure runtime (Context.module_name context) ir

let generate path fmt =
  let module_name = Ortac_core.Utils.module_name_of_path path in
  Gospel.Parser_frontend.parse_ocaml_gospel path
  |> Ortac_core.Utils.type_check [] path
  |> fun (env, sigs) ->
  assert (List.length env = 1);
  let ts = signature ~runtime:"Ortac_runtime" ~module_name (List.hd env) sigs in
  Fmt.pf fmt "%s@.@[<v>%a@]@." 
    header 
    (Ppxlib.Pprintast.structure) 
    ts
