module W = Ortac_core.Warnings
open Ppxlib
open Ortac_core.Builder
open Ir
module Context = Ortac_core.Context

let header =
  "(* This file is generated by ortac quickcheck,\n\
  \   edit the original interface file instead *)"

(** Generate a pattern and variable names for function return values.

    - 0 returns (unit): (ppat_unit (), [])
    - 1 return: (ppat_var "name", ["name"])
    - 2-5 returns: (ppat_tuple [...], ["r1"; "r2"; ...])
    - 6+ returns: None (error case) *)
let return_pattern (returns : Ir.ocaml_var list) : (pattern * string list) option =
  match returns with
  | [] ->
      (* Unit return *)
      Some (ppat_construct (lident "()") None, [])
  | [r] ->
      (* Single return value *)
      Some (pvar r.name, [r.name])
  | ret_list when List.length ret_list <= 5 ->
      (* Tuple return (2-5 values) *)
      let names = List.map (fun (r : Ir.ocaml_var) -> r.name) ret_list in
      let patterns = List.map pvar names in
      Some (ppat_tuple patterns, names)
  | _ ->
      (* Too many return values *)
      None

(* Unwrap the gospel translation from runtime error handling *)
let rec unwrap_runtime_expr (e : expression) : expression =
  match e.pexp_desc with
  | Pexp_try (inner, _) -> 
      (* Strip try-catch blocks used for error reporting *)
      unwrap_runtime_expr inner
  | Pexp_ifthenelse (cond, _, _) ->
      (* For "if not (condition) then error", extract just the condition *)
      (match cond.pexp_desc with
       | Pexp_apply ({ pexp_desc = Pexp_ident { txt = Lident "not"; _ }; _ }, 
                     [(_, inner)]) ->
           unwrap_runtime_expr inner
       | _ -> e)
  | Pexp_sequence (_, rest) ->
      (* Skip error registration calls *)
      unwrap_runtime_expr rest
  | _ -> e

(* Extract just the translated expression from a term *)
let term_to_expr (t : Ir.term) : expression option =
  match t.translation with
  | Error _ -> None
  | Ok e -> Some (unwrap_runtime_expr e)

(** Generate QCheck.assume statements from preconditions.

    Each precondition becomes: QCheck.assume (precond_expr)
    Filters out terms that failed to translate. *)
let generate_assumes (preconditions : Ir.term list) : expression list =
  List.filter_map (fun term ->
    match term_to_expr term with
    | None -> None
    | Some precond_expr ->
        (* Generate: QCheck.assume precond_expr *)
        Some (eapply (evar "QCheck.assume") [precond_expr])
  ) preconditions

(** Generate the property function for a value.

    Structure:
    fun args ->
      QCheck.assume precond1;
      QCheck.assume precond2;
      let ret_pattern = f args in
      postcond1 && postcond2 && ...

    Returns None if:
    - No postconditions (nothing to test)
    - Too many return values (>5)
    - Unsupported return pattern *)
let value_to_property (v : Ir.value) : expression option =
  (* Get the return pattern and variable names *)
  match return_pattern v.returns with
  | None ->
      (* Unsupported return pattern (>5 returns) *)
      Fmt.epr "Warning: Skipping '%s' - too many return values (%d)@."
        v.name (List.length v.returns);
      None
  | Some (ret_pat, _ret_names) ->
      (* Build the function call *)
      let call_args = List.map (fun a -> (a.label, evar a.name)) v.arguments in
      let call = pexp_apply (evar v.name) call_args in

      (* Generate assume statements for preconditions *)
      let assumes = generate_assumes v.preconditions in

      (* Combine all postconditions into a single boolean expression *)
      let postcond_exprs =
        List.filter_map term_to_expr v.postconditions
      in

      let combined_postcond = match postcond_exprs with
        | [] ->
            (* No postconditions found - skip this value *)
            Fmt.epr "Warning: Skipping '%s' - no postconditions to test@." v.name;
            None
        | [ e ] -> Some e
        | exprs ->
            Some (List.fold_left
              (fun acc e -> eapply (evar "(&&)") [ acc; e ])
              (List.hd exprs)
              (List.tl exprs))
      in

      match combined_postcond with
      | None -> None
      | Some postcond ->
          (* Build the function body:
             assumes; let ret = call in postcond *)
          let let_binding =
            pexp_let Nonrecursive
              [ value_binding ~pat:ret_pat ~expr:call ]
              postcond
          in

          (* Prepend assumes to the body *)
          let body = match assumes with
            | [] -> let_binding
            | _ ->
                (* Build: assume1; assume2; ...; let_binding *)
                List.fold_right
                  (fun assume rest -> pexp_sequence assume rest)
                  assumes
                  let_binding
          in

          (* Build the function pattern based on number of arguments:
             - 0 args: fun () -> body
             - 1 arg:  fun x -> body
             - >1 args: fun (x, y, ...) -> body (tuple pattern to match generator) *)
          let fun_pattern = match v.arguments with
            | [] -> ppat_construct (Located.lident "()") None
            | [ a ] -> pvar a.name
            | _multi_args ->
                (* Multiple arguments - use tuple pattern *)
                ppat_tuple (List.map (fun (a : Ir.ocaml_var) -> pvar a.name) v.arguments)
          in

          Some (pexp_fun Nolabel None fun_pattern body)

(* Convert a value specification to property and test structure items *)
let value (v : Ir.value) : Ppxlib.structure_item list =
  (* Generate the property function (call value_to_property only once) *)
  match value_to_property v with
  | None -> []
  | Some prop_expr ->
      let prop_name = v.name ^ "_property" in
      let vb = value_binding ~pat:(pvar prop_name) ~expr:prop_expr in
      let prop_item = pstr_value Nonrecursive [ vb ] in

      (* Generate the test definition *)
      let test_items =
        try
          let generators =
            List.map (fun (arg : Ir.ocaml_var) -> Generators.type_to_generator arg.type_) v.arguments
          in

          let combined_gen = Generators.combine_generators generators in

          let test_name_str = estring v.name in
          let prop_var = evar (v.name ^ "_property") in
          let test_expr =
            [%expr
              QCheck.Test.make
                ~count:100
                ~name:[%e test_name_str]
                [%e combined_gen]
                [%e prop_var]
            ]
          in

          let test_name = v.name ^ "_test" in
          let vb = value_binding ~pat:(pvar test_name) ~expr:test_expr in
          [ pstr_value Nonrecursive [ vb ] ]

        with
        | Generators.Unsupported_custom_type typename ->
            Fmt.epr "Warning: Skipping '%s' - %s@."
              v.name
              (Generators.format_exception (Generators.Unsupported_custom_type typename));
            []
        | Generators.Too_many_arguments n ->
            Fmt.epr "Warning: Skipping '%s' - %s@."
              v.name
              (Generators.format_exception (Generators.Too_many_arguments n));
            []
        | Generators.Unsupported_nested_type typename ->
            Fmt.epr "Warning: Skipping '%s' - %s@."
              v.name
              (Generators.format_exception (Generators.Unsupported_nested_type typename));
            []
      in

      prop_item :: test_items

(** Generate the test runner main function.

    Structure:
    let () = QCheck_base_runner.run_tests_main [test1; test2; ...]

    If test_names is empty, returns None (no tests to run). *)
let test_runner (test_names : string list) : Ppxlib.structure_item option =
  match test_names with
  | [] -> None
  | names ->
      (* Build the list [test1; test2; ...] *)
      let test_list =
        elist (List.map evar names)
      in

      (* Build: QCheck_base_runner.run_tests_main [tests] *)
      let runner_expr =
        [%expr QCheck_base_runner.run_tests_main [%e test_list]]
      in

      (* Build: let () = runner_expr *)
      let vb = value_binding ~pat:(ppat_construct (lident "()") None) ~expr:runner_expr in
      Some (pstr_value Nonrecursive [ vb ])

(* Main structure generation *)
let structure _runtime module_name ir : Ppxlib.structure =
  let include_stmt =
    pmod_ident (lident module_name) |> include_infos |> pstr_include
  in

  (* Generate value items and collect test names in one pass to avoid
     duplicate processing (and duplicate warnings) *)
  let (value_items, test_names) =
    Ir.map_translation ir ~f:(function
      | Ir.Value v ->
          let items = value v in
          (* If we got more than 1 item, we have both property and test *)
          let test_name = if List.length items > 1 then [v.name ^ "_test"] else [] in
          (items, test_name)
      | Ir.Type _ | Ir.Projection _ | Ir.Constant _ | Ir.Function _ | Ir.Predicate _ | Ir.Axiom _ ->
          ([], [])
    )
    |> List.split
    |> fun (items_lists, name_lists) ->
         (List.flatten items_lists, List.flatten name_lists)
  in

  (* Generate test runner *)
  let runner_items = match test_runner test_names with
    | Some runner -> [runner]
    | None -> []
  in

  [include_stmt] @ value_items @ runner_items

let signature ~runtime ~module_name namespace s =
  let open Ortac_core in
  let context = Context.init module_name namespace in
  let ir = Ir_of_gospel.signature ~context s in
  Report.emit_warnings Fmt.stderr ir;
  structure runtime (Context.module_name context) ir

let generate path fmt =
  let module_name = Ortac_core.Utils.module_name_of_path path in
  Gospel.Parser_frontend.parse_ocaml_gospel path
  |> Ortac_core.Utils.type_check [] path
  |> fun (env, sigs) ->
  assert (List.length env = 1);
  let ts = signature ~runtime:"Ortac_runtime" ~module_name (List.hd env) sigs in
  Fmt.pf fmt "%s@.@[<v>%a@]@." 
    header 
    (Ppxlib.Pprintast.structure) 
    ts
